xoffset:
- range: 0-10
  value: 0-0
- range: 10-20
  value: 0-0
yoffset:
- range: 0-10
  value: 20-40
- range: 10-20
  value: 40-20
baseorientation:
- range: 0-10
  value: -0.5--0.5
- range: 10-20
  value: -0.5--0.5
joints:
- j1: 5
  j2: 6
  thetas:
  - range: 0-10
    value: 0.7-0
  - range: 10-20
    value: 0-0.7
- j1: 0
  j2: 1
  thetas:
  - range: 0-10
    value: -0.2--0.3
  - range: 10-20
    value: -0.3--0.2
- j1: 3
  j2: 4
  thetas:
  - range: 0-10
    value: -0.2-0
  - range: 10-20
    value: 0--0.2
- j1: 0
  j2: 7
  thetas:
  - range: 0-10
    value: 0.7-0.5
  - range: 10-20
    value: 0.5-0.7
- j1: 0
  j2: 9
  thetas:
  - range: 0-10
    value: 0-0
  - range: 10-20
    value: 0-0
- j1: 1
  j2: 2
  thetas:
  - range: 0-10
    value: 0.2-0
  - range: 10-20
    value: 0-0.2
- j1: 7
  j2: 8
  thetas:
  - range: 0-10
    value: -0.7-0
  - range: 10-20
    value: 0--0.7
- j1: 0
  j2: 3
  thetas:
  - range: 0-10
    value: 0.2-0.3
  - range: 10-20
    value: 0.3-0.2
- j1: 0
  j2: 5
  thetas:
  - range: 0-10
    value: -0.7--0.5
  - range: 10-20
    value: -0.5--0.7
