frame: 0
save: false
xoffset: 0
yoffset: 20
baseangle: -0.5
jointangles:
  - j1: 0
    j2: 1
    theta: -0.2
  - j1: 0
    j2: 3
    theta: 0.2
  - j1: 0
    j2: 5
    theta: -0.7
  - j1: 0
    j2: 7
    theta: 0.7
  - j1: 0
    j2: 9
    theta: 0
  - j1: 1
    j2: 2
    theta: 0.2
  - j1: 3
    j2: 4
    theta: -0.2
  - j1: 5
    j2: 6
    theta: 0.7
  - j1: 7
    j2: 8
    theta: -0.7
  
  